name: hooky
version: 0.1.0.0
description: See README.md
license: BSD3
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

extra-source-files:
  - README.md

github: brandonchinn178/hooky

default-extensions:
  - ImportQualifiedPost

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

library:
  source-dirs: src
  dependencies:
    - base
    - path
    - path-io
    - text
    - typed-process

executables:
  hooky:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - base
      - hooky
      - optparse-applicative
      - path
      - path-io
      - text
    ghc-options:
      - -threaded

tests:
  hooky-tests:
    main: Main.hs
    source-dirs: test
    dependencies:
      - base
      - hooky
      - path
      - path-io
      - tasty
      - tasty-hunit
      - text
      - typed-process
    ghc-options:
      - -threaded
